### PR TITLE
allow defaults in args without exec

### LINKED ISSUE #104: args tuple error in v5
I'm not sure if this is by design, but I have a lot of decorators that look like this

```python
@decorator
def wrap(func_, *args, **kwargs):
    if not args[-1]:
        new_args = list(args)
        new_args[-1] = ENVIRONMENT_DEPENDENT_VAR
        args = tuple(new_args)
    return func_(*args, **kwargs)

@wrap
def do_stuff(requiredvar, optionalvar=None):
    pass # real work
    return 

```

basically checking if a certain variable is set and, if not, setting it to some appropriate veriable depending on whatever situation.

In v4, when calling `do_stuff(some_var)`

the args value within `wrap` would be `(some_var, None)` 

in v5, 
the args value within `wrap` is now `(some_var, )`

Is this intentional to no longer supply a None (or whatever the function's default is) for named positional arguments?

### PR DESCRIPTION
**Pull request by dschult**
I see a way to get default values in `args` without resorting to `exec` or `eval`.
It uses `inspect.signature.bind` which has an `apply_defaults` method.

fixes #104   I'm not sure about #103

### CODE REVIEW

**Comment by dschult** [comment]
Maybe `decorator` could provide both possible behaviors with either two functions or a parameter to designate which you want?

```python
@decorator(with_defaults=True)
def my_dec.........
```
???

The test failures are the documentation examples which show the new behavior which isn't there anymore.
Feel free to use this however you want including closing it -- or closing it and implementing something similar/better.

**Comment by dschult** [comment]
Another advantage of using `signature.bind` is that it leaves the decision about whether arguments are position or keyword arguments up to the builtin inspect module and removes it from `decorator`.   :}

We'd still have to figure out whether to include default values for arguments of course. Leaving the defaults out of `args` makes it hard to massage the default values in the decorator.  What is the advantage to leaving the default values out of `args`?

**Comment by micheles** [comment]
I like this :-) Thanks for the idea, it is implemented here now: https://github.com/micheles/decorator/pull/108
Happy Easter!

**Comment by dschult** [comment]
Thanks for the implementation in #108 but the default values don't seem to be propagated to the `args`.
Did you mean to leave out a line from `fix` that does `ba.apply_defaults()`?

If the `fix` code is correct, what idiom do you suggest for processing `args` after the default values are applied but before the decorated function is called?

**Pull request closed without merging**
