### PR TITLE
Add support for Python 3.13

### PR DESCRIPTION
**Pull request by hugovk**
Python 3.13 is due out today! 🚀 

https://peps.python.org/pep-0719/

### CODE REVIEW

**Comment by micheles** [comment]
Thanks for your timely contribution!

**Comment by marniwild** [comment]
Hi @micheles will support for 3.13 be released? We are currently using 5.1.1 with our project. Thanks

**Comment by micheles** [comment]
I need to find the time to make a new release. It is due anyway, so stay tuned.

**Comment by micheles** [comment]
decorator 5.3.2 was released yesterday and it supports Python 3.13 :-)

**Pull request merged**
