### PR TITLE
Drop support for EOL Python versions

### PR DESCRIPTION
**Pull request by hugovk**
Python 2.6 to 3.3 are EOL and no longer receiving security updates (or any updates) from the core Python team for quite some time:

Version | EOL date
--- | ---
2.6 | 2013-10-29
3.0 | 2009-06-27
3.1 | 2012-04-09
3.2 | 2016-02-27
3.3 | 2017-09-29

They're also relatively little used. Here's the pip installs for decorator from PyPI for July 2018:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 3.6            |  40.82% |        958,846 |
| 2.7            |  39.22% |        921,199 |
| 3.5            |  13.21% |        310,208 |
| 3.4            |   3.92% |         92,134 |
| 3.7            |   1.89% |         44,332 |
| 2.6            |   0.93% |         21,878 |
| 3.3            |   0.01% |            246 |
| 3.8            |   0.00% |             67 |
| 3.2            |   0.00% |              8 |
| None           |   0.00% |              1 |
| Total          |         |      2,348,919 |

Source: `pypinfo --start-date 2018-07-01 --end-date 2018-07-31 --percent --markdown decorator pyversion`

This PR drops support for EOL versions, removes redundant code and modernises some code to use newer Python features. It also adds `python_requires` to setup.py to help pip install the right version of decorator for the user's Python version.

### CODE REVIEW

**Comment by micheles** [comment]
I thank you for your contribution, however your data says that I would make unhappy the people behind the 21,878 downloads of Python 2.6. Why should I do that? Moreover, the %s format is not deprecated, even in the most recent Python, so I do not see any point in changing it with the {}.format syntax. Perhaps after 2020 I will drop support for Python 2 (but perhaps not). In any case I am not in hurry of annoying my users. The decorator module value stability.

**Comment by hugovk** [comment]
Hello, that's absolutely fine if you still want to support older versions :)

The download figures are not necessarily individual people, they can be CI install or other things. But yes, 21k is still quite large, even if it's a tiny proportion of 2.4 million :)

`python_requires` would ensure people on unsupported Python would still get the last version of decorator that did support that version. See https://packaging.python.org/guides/dropping-older-python-versions/ It's probably a good idea to add this anyway, for those versions which are supported.

The %s is documented as obsolete in the Python 3.0 docs:

> **Note:** The formatting operations described here are obsolete and may go away in future versions of Python. Use the new [_String Formatting_](https://docs.python.org/release/3.0/library/string.html#string-formatting) in new code.

https://docs.python.org/release/3.0/library/stdtypes.html#old-string-formatting-operations

I can remove those changes if you like.

If 2.6 is still needed, how do you feel about dropping 3.0 to 3.3?

Thanks for your time!

**Comment by micheles** [comment]
> python_requires would ensure people on unsupported Python would still get the last version of decorator that did support that version. See https://packaging.python.org/guides/dropping-older-python-versions/ It's probably a good idea to add this anyway, for those versions which are supported.

That's good, I will add it myself.

> The %s is documented as obsolete in the Python 3.0 docs

Yes, that was the plan, but if I remember correctly they undeprecated it later on, this is why it is still there in Python 3.7. But I may be remembering incorrectly.

**Comment by hugovk** [comment]
> Yes, that was the plan, but if I remember correctly they undeprecated it later on, this is why it is still there in Python 3.7.

Aha, you remember correctly: the 3.7 docs now only give a warning to be careful with `%` formatting.

https://docs.python.org/3.7/library/stdtypes.html#printf-style-string-formatting

Thanks!

**Comment by micheles** [comment]
I have added python_requires to the setup.py and now I am closing your PR.

**Pull request closed without merging**
