### PR TITLE
Add support for Python 3.12

### PR DESCRIPTION
**Pull request by hugovk**
The [Python 3.12 release candidate is out!](https://discuss.python.org/t/python-3-12-0-release-candidate-1-released/31137?u=hugovk) :rocket:

> ## Call to action
> 
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.12 compatibilities during this phase, and where necessary publish Python 3.12 wheels on PyPI to be ready for the final release of 3.12.0.

### CODE REVIEW

**Comment by micheles** [comment]
It looks like you need to disable the tests for python 3.5 and 3.6

**Comment by hugovk** [comment]
Updated! What do you think about dropping support for 3.5 and 3.6? They've been EOL for a few years:

| cycle |  release   | latest  | latest release |  support   |    eol     |
|:------|:----------:|:--------|:--------------:|:----------:|:----------:|
| 3.11  | 2022-10-24 | 3.11.4  |   2023-06-06   | 2024-04-01 | 2027-10-24 |
| 3.10  | 2021-10-04 | 3.10.12 |   2023-06-06   | 2023-04-05 | 2026-10-04 |
| 3.9   | 2020-10-05 | 3.9.17  |   2023-06-06   | 2022-05-17 | 2025-10-05 |
| 3.8   | 2019-10-14 | 3.8.17  |   2023-06-06   | 2021-05-03 | 2024-10-14 |
| 3.7   | 2018-06-26 | 3.7.17  |   2023-06-05   | 2020-06-27 | 2023-06-27 |
| 3.6   | 2016-12-22 | 3.6.15  |   2021-09-03   | 2018-12-24 | 2021-12-23 |
| 3.5   | 2015-09-12 | 3.5.10  |   2020-09-05   |   False    | 2020-09-13 |

3.7 also recently went EOL.

**Comment by micheles** [comment]
Yep, I will have to drop support for the versions that I cannot test with the actions.

**Comment by hugovk** [comment]
I've pushed a couple of commits to drop 3.5 and 3.6. 

The first is the simple removal, and the second runs the pyupgrade tool to update the syntax for 3.7+.

**Comment by micheles** [comment]
I did not know about pyupgrade tool. I am not sure I am happy. When I said "I will remove the support for python 3.5, 3.6" I meant I will not support anymore users having issues with older versions of Python, not "I will intentionally break the decorator module for people using old versions", which is what pyupdate is doing. That is not nice.

**Comment by micheles** [comment]
I was not clear. I am happy with your changes (requires>=3.7 and changing the docs saying that only >= 3.7 is supported), I was not happy with pyupgrade which is gratuitously breaking the syntax. The old string formatting syntax works, AFAIK is not deprecated, and there is no need to change it. Then somebody can just copy the module, put on his Python path and it would work even with old versions of Python. I will not claim to support them, but I will not actively break them.

**Pull request merged**
