### PR TITLE
do not copy wrapped function's globals

### PR DESCRIPTION
**Pull request by gutworth**
The decorator module currently copies a functions globals to evaluate the source template in. Having multiple copies of a module's globals around is bad. It can lead to subtle memory leaks. Instead, we should just evaluate the generated function in the wrapped function's globals. However, the decorator module also uses globals to pass in magical objects such as _decorate_ and _func_. To continue to pass these in, we wrap the generated function in an outer function and use closures.

### CODE REVIEW

**Comment by micheles** [comment]
I would be curious to see a case when the memory leak happens, just for my personal enlightment. Can you provide an example?

**Comment by gutworth** [comment]
The case I ran into was more complicated, but the basic idea is something like this:
```
some_memory_intensive_thing = f()
...
@decorator
def my_dec():
    pass
....
del some_memory_intensive_thing
```
Then `my_dec` ends up holding onto `some_memory_intensive_thing` forever!

In general, I think hanging onto copy of (probably half-constructed) module's globals is a bad idea.

**Comment by micheles** [comment]
Superseded by https://github.com/micheles/decorator/pull/20

It seems that I don't need to copy the globals after all, so there is no need to use a closure. Let me know if this works for you.

**Comment by gutworth** [comment]
Yeah, #20 is another way to shave the cat. Thanks!

**Pull request closed without merging**
