### PR TITLE
Issue#93 Implement support for class methods as decorators

### PR DESCRIPTION
**Pull request by joaoe**
The title explains it :)

### CODE REVIEW

**Comment by joaoe** [comment]
It fails in the documentation test because it apparently oes not like that I expanded the docstring.
What is that test about ? I see that the documentation is duplicated in tests/documentation.py

**Comment by micheles** [comment]
Sorry that you spent all this effort, but there is no way I will accept this contribution. By design the decorator module is meant to be used on functions and on functions only. If you read the documentation you will see the following sentence:
"""
In the present implementation, decorators generated by ``decorator``
can only be used on user-defined Python functions or methods.
They cannot be used on generic callable objects or built-in functions,
due to limitations of the standard library's ``inspect`` module, especially
for Python 2. In Python 3.5, many such limitations have been removed, but
I still think that it is cleaner and safer to decorate only functions and
coroutines. If you want to decorate things like classmethods/staticmethods
and general callables - which I will never support in the decorator module -
I suggest you to look at the [wrapt](https://wrapt.readthedocs.io/en/latest/)
project by Graeme Dumpleton.
"""

**Comment by joaoe** [comment]
> They cannot be used on generic callable objects or built-in functions,
> due to limitations of the standard library's inspect module, especially
> for Python 2.

How is this an issue if I implemented support for everything working in python 2 and 3 and with unit tests ?

**Comment by micheles** [comment]
Does not matter. Even if your implementation works perfectly against all versions of Python it is against the goal of the decorator module of being simple and doing only one thing well (i.e. decorating functions, not descriptors). You are not the first to want to be able to do this kinds of things and Graeme Dumpleton wrote a huge module just to do that. The documentation I quoted before is quite clear and was written years ago. I have not changed my mind.

**Pull request closed without merging**
